name: File Check
description: ファイルチェック

inputs:
  branch:
    description: ブランチ名
    required: true
  files:
    description: 処理対象ファイルのリスト
    required: true
  project-files:
    description: 処理対象プロジェクトのリスト
    required: true

runs:
  using: composite

  steps:
    - name: File Check
      shell: cmd
      run: |
        dotnet-script "${{ github.action_path }}/CheckFiles.csx" ${{ inputs.branch }} ${{ inputs.files }} ${{ inputs.project-files }}
