name: Checkout
description: 呼び出し元リポジトリのチェックアウト

outputs:
  branch:
    description: 対象のブランチ名
    value: ${{ steps.branch.outputs.branch }}

runs:
  using: composite
  steps:
    - id: branch
      shell: pwsh
      run: |
        "branch=${{ github.event.pull_request.head.ref || github.ref_name }}" >> $env:GITHUB_OUTPUT

    - uses: actions/checkout@v7
      with:
        ref: ${{ steps.branch.outputs.branch }}
