name: Diff
description: 差分を取得する

outputs:
  changed_files:
    description: 差分ファイルのリスト
    value: ${{ steps.changed_files.outputs.changed_files }}
  changed_projects:
    description: 差分プロジェクトの .vbproj のリスト
    value: ${{ steps.changed_projects.outputs.changed_projects }}

runs:
  using: composite

  steps:
    # 差分ファイルを取得
    - name: Get Changed Files
      uses: dorny/paths-filter@v4.0.3
      id: changed_files_relative
      with:
        list-files: shell
        filters: |
            changed:
              - '**'

    - name: Convert To Absolute Path
      id: changed_files
      shell: cmd
      run: |
        dotnet-script "${{ github.action_path }}/ChangedFiles.csx" "${{ github.workspace }}" ${{ steps.changed_files_relative.outputs.changed_files }}

    # 差分プロジェクトの .vbproj を取得
    - name: Get Changed Projects
      id: changed_projects
      shell: cmd
      run: |
        dotnet-script "${{ github.action_path }}/ChangedProjects.csx" ${{ steps.changed_files.outputs.changed_files }}

    # 出力
    - name: Output
      shell: cmd
      run: |
        echo steps.changed_files.outputs.changed_files : ${{ steps.changed_files.outputs.changed_files }}
        echo steps.changed_projects.outputs.changed_projects : ${{ steps.changed_projects.outputs.changed_projects }}
