name: Toko

on:
  # 各モジュールから呼び出されたときに実行
  workflow_call:

jobs:
  main:
    runs-on: self-hosted

    steps:
      - name: Info
        shell: cmd
        run: |
            set GITHUB_

      - name: Initialize Summary
        uses: wiseman-fukushi2-trial/actions/actions/initialize-summary@DX-RKuji

      # 呼び出し元リポジトリをクローン
      - name: Checkout
        uses: wiseman-fukushi2-trial/actions/actions/checkout@DX-RKuji

      # 変更を取得
      # ${{ steps.diff.outputs.changed_files }} : 差分ファイルのリスト
      # ${{ steps.diff.outputs.changed_projects }} : 差分プロジェクトの .vbproj のリスト
      - name: Get Diff
        uses: wiseman-fukushi2-trial/actions/actions/diff@DX-RKuji
        id: diff

      # ビルド
      - name: Build
        uses: wiseman-fukushi2-trial/actions/actions/build@DX-RKuji
        with:
          project-files: ${{ steps.diff.outputs.changed_projects }}

      # ファイルチェック
      - name: File Check
        uses: wiseman-fukushi2-trial/actions/actions/file-check@DX-RKuji
        with:
          files: ${{ steps.diff.outputs.changed_files }}
